DB_URL = "postgresql+psycopg2://postgres:!Q2w3e4r5t@localhost:5432/MTBA"

# 원본 파일 경로
RUNTIME_XLSX = "D:/PythonProject/Project/MTBA_Streamlit/Data/Runtime_summary_by_date.xlsx"
ALARM_DAILY_XLSX = "D:/PythonProject/Project/MTBA_Streamlit/Data/alarm_count_filter_sum.xlsx"
ALARM_DETAIL_XLSX = "D:/PythonProject/Project/MTBA_Streamlit/Data/alarm_count_filter.xlsx"
ALARM_MASTER_XLSX = "D:/PythonProject/Project/MTBA_Streamlit/Data/Master_Result.xlsx"
PRODUCTION_CSV = "D:/PythonProject/Project/MTBA_Streamlit/Data/MTBA_Production.csv"

[db]
host = "localhost"
name = "auth"
user = "postgres"
password = "!Q2w3e4r5t"
port = 5432

[cookie]
password = "MTBA_SUPER_SECRET_2026_LOGIN_COOKIE_KEY_!@#"